name: InvasionHoes
version: 2.2
main: net.invasionpvp.harmlesscat.FactionHandHoes
api-version: 1.16
depend:
  - Factions
  - PlaceholderAPI
  - Vault
commands:
  hoes:
    aliases:
      - hoe
  ahoes:
    aliases:
       - ahoe
  cane:
    aliases:
      - scane